# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "▸▹" # "[▸▹ ](dimmed white)"

format = """
[╭](fg:current_line)\
$os\
$directory\

$fill \

$git_branch\
$python\

$line_break\

$sudo\
$character"""

palette = 'dracula'

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue = '#6272A4'
cyan = '#8BE9FD'
green = '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red = '#FF5555'
yellow = '#F1FA8C'

[os]
format = '(fg:current_line)[$symbol ](fg:foreground)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[λ](fg:bold white)'
error_symbol = '[✗](fg:bold red)'

[custom.flutter_version]
description = "Flutter version"
command = "grep -o '\"flutter\": \"[^\"]*\"' .fvmrc | grep -o '[0-9.]*'"
detect_files = [".fvmrc"]
symbol = ""
format = '[ $symbol $output]($style)'

[dart]
symbol = ""
format = " [$symbol $version ]($style)"

[directory]
truncation_length = 999
truncate_to_repo = false
read_only = ""
use_os_path_sep = true
style = "bold blue"
format = '[$path ]($style)'

[fill]
symbol = '-'
style = "fg:current_line"

[git_branch]
format = "[$symbol $branch]($style)"
symbol = ""
style = "bold bright-cyan"
only_attached = true

[gradle]
format = '[ $symbol $version]($style)'
symbol = ""

[java]
symbol = ""
style = "bold dimmed white"
format = "[( [$symbol](white) $version )]($style)"

[ruby]
format = "[$symbol $version]($style)"
symbol = ""
style = "bold red"

[sudo]
format = "[$symbol]($style)"
style = "bold bright-purple"
symbol = "⚡"
disabled = false
